apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:hub-cluster-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:hub-cluster-controller
subjects:
  - kind: ServiceAccount
    name: hub-cluster-controller-sa
    namespace: open-cluster-management
